version: '2'

# 定义服务
services:
    db:
        image: mysql:5.6
        container_name: ecjia-daojia-db
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ecjia@ecjia.com
            MYSQL_DATABASE: ecjia-daojia
            MYSQL_USER: ecjia
            MYSQL_PASSWORD: ecjiadaojia123

    phpmyadmin:
        depends_on:
            - db
        image: corbinu/docker-phpmyadmin
        container_name: ecjia-daojia-phpmyadmin
        links:
            - db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: ecjia@ecjia.com
            MYSQL_PORT_3306_TCP_ADDR: db
            MYSQL_PORT_3306_TCP_PORT: 3306

    php-fpm:
        depends_on:
            - db
        container_name: ecjia-daojia-php
        build:
            context: ./services/php-fpm
            args:
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
                - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
                - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
                - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
                - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
                - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
                - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
                - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
                - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
                - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
            dockerfile: "Dockerfile-${PHP_VERSION}"
        volumes:
            - "./www:/data/www"
            - "./uploads:/data/www/content/uploads"
            - "./storages:/data/www/content/storages"
            - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        links:
            - db
        expose:
            - "9000"
        restart: always

    web:
        container_name: ecjia-daojia
        build:
            context: ./services/nginx
            args:
                - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
                - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - "./www:/data/www"
            - "./uploads:/data/www/content/uploads"
            - "./storages:/data/www/content/storages"
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
